services:
  api:
    image: api\
    container_name: api
    build:
      context: .
      dockerfile: Api/Dockerfile
      ports:
        - "8080:8080"
        - "8081:8081"
        
  api.database:
    image: postgres:latest
    container_name: api.database
      
      
